### ISSUE TITLE
const-ref em double

### ISSUE THREAD

**Issue by tcanabrava** [andreagen0r/ColorWheel#1]
https://github.com/andreagen0r/ColorWheel/blob/1143d4cb78a7374e1ee0b0a37ed57c4fab3abc41/colorwheel.h#L29

Doubles nao devem ser passados por const ref, mas sim por valor. Passar tudo por const-ref reduz a velocidade de codigo, e deve ser utilizado apenas quando a variavel nao eh homogenea, ou nao eh POD.

http://www.macieira.org/blog/2012/02/the-value-of-passing-by-value/

Recommendations for code

    Structures of up to 16 bytes containing integers and pointers should be passed by value;
    Homogeneous structures of up to 16 bytes containing floating-point should be passed by value (2 doubles or 4 floats);
    Mixed-type structures should be avoided; if they exist, passing by value is still a good idea;

The above is only valid for structures that are trivially-copiable and trivially-destrucitble. All C structures (POD in C++) meet those criteria.

**Comment by andreagen0r** [comment]
Fiz as alterações necessária e melhorou a performance, se puder de uma olhada novamente.
