### ISSUE TITLE
Estilo de Conexao antiga

### ISSUE THREAD

**Issue by tcanabrava** [andreagen0r/ColorWheel#3]
https://github.com/andreagen0r/ColorWheel/blob/c27ef8c30998736dafe5bdcbacc4b3eb7b34f4bc/form.cpp#L17-L18

O estilo de conexao utilizada, com SIGNAL() e SLOT() foi deprecado no Qt4,no Qt5 temos um que funciona mais rapido (pois nao tem que fazer analize de string, indo direto pro ponteiro do metodo)

caso voce tenha um slot:
connect( obj, &ClasseSender::signal, receiver, &ClasseReceiver::slot);

caso voce goste de slots inline, um buttonclick:
connect( obj, &QPushButton::clicked, [this]{
     qDebug() << "Clicked!"
});

**Comment by andreagen0r** [comment]
é isso aqui?
// Old
connect(ui->widget, SIGNAL(colorChanged(QColor)), this, SLOT(cor(QColor)));
// New
connect(ui->widget, &ColorWheel::colorChanged, this, &Form::cor);
